name: "Automatic build"
on:
  push:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  continuous-delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Verify Ruby and Bundler
        run: |
          ruby -v
          bundler -v
      - name: Deploy
        run: bash tools/deploy.sh

      - name: Debug Deployment
        if: failure() # Run only if a step fails
        run: |
          echo "Deployment failed. Debugging..."
          ls -la
